# DSKYpoly Docker Configuration
# Docker Compose for multi-container mathematical computation environment

version: '3.8'

services:
  # Main development environment
  dskypoly-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dskypoly-mathematical-workspace
    image: dskypoly:latest
    volumes:
      - .:/workspace
      - dskypoly-data:/data
    ports:
      - "8080:8080"  # For potential web interface
    environment:
      - DISPLAY=host.docker.internal:0.0  # For GUI apps on Windows
      - TERM=xterm-256color
    stdin_open: true
    tty: true
    working_dir: /workspace
    command: /bin/bash

  # Analytics environment with Jupyter
  dskypoly-analytics:
    build:
      context: .
      dockerfile: Dockerfile.analytics
    container_name: dskypoly-analytics
    volumes:
      - .:/workspace
      - dskypoly-data:/data
    ports:
      - "8888:8888"  # Jupyter notebook
    environment:
      - JUPYTER_ENABLE_LAB=yes
    depends_on:
      - dskypoly-dev

volumes:
  dskypoly-data:
    driver: local

networks:
  default:
    name: dskypoly-network
